/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Excessoes.CamposObrigatoriosNaoPreenchidosException;
import Excessoes.SenhaEConfirmacaoDeSenhaDiferentesException;
import Excessoes.UsuarioJaCadastradoException;
import control.Controle;
import enums.Sexo;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author NildoJunior
 */
public class TelaCadastro extends javax.swing.JFrame {
    private Controle controle;
    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        controle = Controle.getInstance();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioGrupSexo = new javax.swing.ButtonGroup();
        labelLogin = new javax.swing.JLabel();
        labelSenha = new javax.swing.JLabel();
        labelConfirmacaoSenha = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        labelCPF = new javax.swing.JLabel();
        labelDataNasc = new javax.swing.JLabel();
        labelSexo = new javax.swing.JLabel();
        campoTextoLogin = new javax.swing.JTextField();
        campoTextoSenha = new javax.swing.JPasswordField();
        campoTextoConfirmacaoSenha = new javax.swing.JPasswordField();
        campoTextoNome = new javax.swing.JTextField();
        try{
            campoTextoCpf = new javax.swing.JFormattedTextField(new MaskFormatter("###.###.###-##"));
            campoTextoDataNasc = new javax.swing.JFormattedTextField(new MaskFormatter("##/##/####"));
            radioSexoFeminino = new javax.swing.JRadioButton();
            radioSexoMasculino = new javax.swing.JRadioButton();
            botaoOk = new javax.swing.JButton();
            botaoCancelar = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
            setTitle("Jogo da memória - One Piece");
            setAlwaysOnTop(true);
            setBackground(new java.awt.Color(255, 255, 255));

            labelLogin.setText("Login:");

            labelSenha.setText("Senha:");

            labelConfirmacaoSenha.setText("Confirmação de senha:");

            labelNome.setText("Nome:");

            labelCPF.setText("CPF:");

            labelDataNasc.setText("Data de nascimento:");

            labelSexo.setText("Sexo:");

        }catch(ParseException e){}

        radioGrupSexo.add(radioSexoFeminino);
        radioSexoFeminino.setText("Feminino");

        radioGrupSexo.add(radioSexoMasculino);
        radioSexoMasculino.setText("Masculino");

        botaoOk.setText("Ok");
        botaoOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoOkActionPerformed(evt);
            }
        });

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoOk, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSexo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelDataNasc, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelCPF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelNome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelConfirmacaoSenha, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelSenha, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelLogin, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioSexoFeminino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioSexoMasculino))
                            .addComponent(campoTextoLogin)
                            .addComponent(campoTextoSenha)
                            .addComponent(campoTextoConfirmacaoSenha)
                            .addComponent(campoTextoNome)
                            .addComponent(campoTextoCpf)
                            .addComponent(campoTextoDataNasc))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLogin)
                    .addComponent(campoTextoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSenha)
                    .addComponent(campoTextoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelConfirmacaoSenha)
                    .addComponent(campoTextoConfirmacaoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(campoTextoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCPF)
                    .addComponent(campoTextoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDataNasc)
                    .addComponent(campoTextoDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSexo)
                    .addComponent(radioSexoFeminino)
                    .addComponent(radioSexoMasculino))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoOk)
                    .addComponent(botaoCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
       this.dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void botaoOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoOkActionPerformed
        try {
            controle.adicionarUsuario(this.campoTextoLogin.getText(), String.valueOf(this.campoTextoSenha.getPassword()),
                    String.valueOf(this.campoTextoConfirmacaoSenha.getPassword()), this.campoTextoNome.getText(),
                    this.campoTextoCpf.getText(), this.campoTextoDataNasc.getText(), getSexoSelecionado());
            this.dispose();
            this.mostrarMensagemErro("Cadastro realizado com sucesso");
        } catch (UsuarioJaCadastradoException ex) {
            this.mostrarMensagemErro(ex.getMessage());
        } catch (SenhaEConfirmacaoDeSenhaDiferentesException ex) {
            this.mostrarMensagemErro(ex.getMessage());
        } catch (CamposObrigatoriosNaoPreenchidosException ex) {
            this.mostrarMensagemErro(ex.getMessage());
        }
    }//GEN-LAST:event_botaoOkActionPerformed

    private Sexo getSexoSelecionado(){
        Sexo sexoSelecionado;
        if(radioSexoFeminino.isSelected()){
            sexoSelecionado = Sexo.FEMININO;
        }
        else{
            if(radioSexoMasculino.isSelected()){
                sexoSelecionado = Sexo.MASCULINO;
            }
            else{
                sexoSelecionado = null;
            }
        }
        return sexoSelecionado;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoOk;
    private javax.swing.JPasswordField campoTextoConfirmacaoSenha;
    private javax.swing.JFormattedTextField campoTextoCpf;
    private javax.swing.JFormattedTextField campoTextoDataNasc;
    private javax.swing.JTextField campoTextoLogin;
    private javax.swing.JTextField campoTextoNome;
    private javax.swing.JPasswordField campoTextoSenha;
    private javax.swing.JLabel labelCPF;
    private javax.swing.JLabel labelConfirmacaoSenha;
    private javax.swing.JLabel labelDataNasc;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelSexo;
    private javax.swing.ButtonGroup radioGrupSexo;
    private javax.swing.JRadioButton radioSexoFeminino;
    private javax.swing.JRadioButton radioSexoMasculino;
    // End of variables declaration//GEN-END:variables

    private void mostrarMensagemErro(String msg){
        JOptionPane.showMessageDialog(rootPane, msg);
    }

    private void limparCampos(){
        this.campoTextoLogin.setText("");
        this.campoTextoSenha.setText("");
        this.campoTextoConfirmacaoSenha.setText("");
        this.campoTextoNome.setText("");
        this.campoTextoCpf.setText("");
        this.campoTextoDataNasc.setText("");
        this.radioGrupSexo.clearSelection();
    }
}
